title: RSE International Survey {{year}}
remote_theme: pmarsceill/just-the-docs
description: >- # this means to ignore newlines until "baseurl:"
  International Research Software Engineering survey ({{year}})
baseurl: "/international-survey-{{year}}" # the subpath of your site, e.g. /blog
url: "https://softwaresaved.github.io"

theme: just-the-docs
search_enabled: true
color_scheme: survey
exclude: ["*.py", "vendor"]

collections:
  section:
    permalink: "/:collection/:path/"
    output: true
  country:
    permalink: "/:collection/:path/"
    output: true

kramdown:
  toc_levels: 2..2

back_to_top: true
back_to_top_text: "Back to top"


footer_content: "Copyright &copy; {{year}} Software Sustainability Institute, <a href=\"https://github.com/softwaresaved/international-survey-{{year}}/blob/main/LICENSE\">BSD 3-Clause License</a>"

aux_links:
  "Source on GitHub":
    - "//github.com/softwaresaved/international-survey-{{year}}"

just_the_docs:
  collections:
    section:
      name: Section
      nav_exclude: false
      search_exclude: false
    country:
      name: Country
      nav_exclude: false
      search_exclude: false
